/**
 * Emits JSON seed payload for scripts/seed-services-page-lists.mjs (stdout only).
 */
import {
  fallbackDeliverablesAsCmsItems,
  fallbackProcessStepsAsCmsItems,
  fallbackServiceLayersAsCmsItems,
} from "../astro-app/src/lib/services-page-fallbacks.ts";

/** Matches live /services template fallbacks when CMS fields are empty. */
const sectionText: Record<string, Record<string, string>> = {
  serviceSystemEyebrow: {
    en: "Service system",
    tr: "Hizmet yapısı",
    de: "Service-System",
    fr: "Système de services",
    es: "Sistema de servicios",
    it: "Sistema di servizi",
    ar: "هيكل الخدمات",
    ja: "サービス構成",
  },
  serviceSystemTitle: {
    en: "Choose one layer, or build the whole stack.",
    tr: "Tek bir katmanı seçin ya da tüm sistemi birlikte kurun.",
    de: "Wählen Sie einen Layer oder bauen Sie den ganzen Stack.",
    fr: "Choisissez un layer ou construisez tout le stack.",
    es: "Elija una capa o construya todo el stack.",
    it: "Scegli un layer o costruisci l’intero stack.",
    ar: "اختر طبقة واحدة أو ابنِ الـ stack بالكامل.",
    ja: "一つのレイヤーだけでも、全体のスタック構築でも対応します。",
  },
  serviceSystemLead: {
    en: "The services are grouped by product layer, so buyers can quickly understand where WillowSoft fits.",
    tr: "Hizmetler ürün katmanlarına göre ayrılır; böylece WillowSoft'un projede nerede değer katacağı hızlıca anlaşılır.",
    de: "Die Services sind nach Produkt-Layern gruppiert, damit schnell klar wird, wo WillowSoft ins Projekt passt.",
    fr: "Les services sont regroupés par layer produit afin de voir rapidement où WillowSoft apporte de la valeur.",
    es: "Los servicios se agrupan por capa de producto para entender rápido dónde encaja WillowSoft.",
    it: "I servizi sono raggruppati per layer di prodotto, così è chiaro dove WillowSoft porta valore.",
    ar: "نرتّب الخدمات حسب طبقات المنتج حتى يتضح سريعًا أين تضيف WillowSoft قيمة.",
    ja: "サービスは製品レイヤーごとに整理され、WillowSoft がどこで価値を出せるかをすぐ把握できます。",
  },
  deliverablesEyebrow: {
    en: "Deliverables",
    tr: "Teslimatlar",
    de: "Deliverables",
    fr: "Livrables",
    es: "Entregables",
    it: "Deliverable",
    ar: "المخرجات",
    ja: "納品物",
  },
  deliverablesTitle: {
    en: "What leaves the project, layer by layer.",
    tr: "Projeden çıkan teslimatlar, katman katman.",
    de: "Was aus dem Projekt hervorgeht, Layer für Layer.",
    fr: "Ce qui sort du projet, layer par layer.",
    es: "Lo que entrega el proyecto, capa por capa.",
    it: "Cosa viene consegnato dal progetto, layer per layer.",
    ar: "ما يخرج من المشروع، طبقة بطبقة.",
    ja: "プロジェクトから生まれる成果物をレイヤーごとに。",
  },
  deliverablesLead: {
    en: "The deliverables are practical: source files, firmware, APIs, data models, dashboards and deployment documentation.",
    tr: "Teslimatlar doğrudan kullanılabilir varlıklardır: kaynak dosyaları, firmware, API'ler, veri modelleri, dashboard'lar ve deployment dokümantasyonu.",
    de: "Die Deliverables sind praktisch nutzbar: Quelldateien, Firmware, APIs, Datenmodelle, Dashboards und Deployment-Dokumentation.",
    fr: "Les livrables sont concrets : fichiers source, firmware, API, modèles de données, dashboards et documentation de deployment.",
    es: "Los entregables son prácticos: archivos fuente, firmware, API, modelos de datos, dashboards y documentación de deployment.",
    it: "I deliverable sono pratici: file sorgente, firmware, API, modelli dati, dashboard e documentazione di deployment.",
    ar: "المخرجات عملية: ملفات مصدر، وfirmware، وAPIs، ونماذج بيانات، وdashboards، ووثائق deployment.",
    ja: "納品物は実用的なものです。ソースファイル、ファームウェア、API、データモデル、ダッシュボード、デプロイ資料など。",
  },
  handoffTitle: {
    en: "Project handoff",
    tr: "Proje devri",
    de: "Projektübergabe",
    fr: "Handoff projet",
    es: "Traspaso del proyecto",
    it: "Handoff del progetto",
    ar: "تسليم المشروع",
    ja: "プロジェクト引き渡し",
  },
  handoffDesc: {
    en: "Every layer is documented so your internal team can operate, extend and audit the system.",
    tr: "Her katman dokümante edilir; böylece ekibiniz sistemi işletebilir, geliştirebilir ve denetleyebilir.",
    de: "Jeder Layer wird dokumentiert, damit Ihr internes Team das System betreiben, erweitern und prüfen kann.",
    fr: "Chaque layer est documenté pour que votre équipe puisse exploiter, faire évoluer et auditer le système.",
    es: "Cada capa queda documentada para que su equipo pueda operar, ampliar y auditar el sistema.",
    it: "Ogni layer è documentato, così il team interno può gestire, estendere e auditare il sistema.",
    ar: "نوثّق كل طبقة حتى يستطيع فريقك تشغيل النظام وتوسيعه وتدقيقه.",
    ja: "各レイヤーを文書化し、社内チームが運用、拡張、監査できる状態にします。",
  },
  caseStudiesEyebrow: {
    en: "Case Studies",
    tr: "Vaka çalışmaları",
    de: "Case Studies",
    fr: "Cas clients",
    es: "Casos de estudio",
    it: "Case study",
    ar: "دراسات حالة",
    ja: "導入事例",
  },
  caseStudiesTitle: {
    en: "Proven in production.",
    tr: "Sahada kanıtlanmış işler.",
    de: "In Produktion bewährt.",
    fr: "Prouvé en production.",
    es: "Probado en producción.",
    it: "Validato in produzione.",
    ar: "مثبت في بيئات الإنتاج.",
    ja: "本番環境で実証済み。",
  },
  caseStudiesLead: {
    en: "See how WillowSoft's integrated hardware, firmware, and digital stack delivers measurable operational ROI for our clients.",
    tr: "WillowSoft'un entegre donanım, firmware ve dijital stack yaklaşımının müşteriler için nasıl ölçülebilir operasyonel değer ürettiğini görün.",
    de: "Sehen Sie, wie WillowSofts integrierter Hardware-, Firmware- und Digital-Stack messbaren operativen ROI liefert.",
    fr: "Découvrez comment le stack intégré hardware, firmware et digital de WillowSoft crée un ROI opérationnel mesurable.",
    es: "Vea cómo el stack integrado de hardware, firmware y digital de WillowSoft genera ROI operativo medible.",
    it: "Scopri come lo stack integrato hardware, firmware e digitale di WillowSoft genera ROI operativo misurabile.",
    ar: "تعرّف كيف يحقق stack WillowSoft المتكامل من hardware وfirmware والأنظمة الرقمية قيمة تشغيلية قابلة للقياس.",
    ja: "WillowSoft のハードウェア、ファームウェア、デジタルスタック統合が、測定可能な運用価値をどう生むかをご覧ください。",
  },
  ctaEyebrow: {
    en: "Start with engineering",
    tr: "Mühendislikle başlayın",
    de: "Mit Engineering starten",
    fr: "Commencer avec l’ingénierie",
    es: "Empiece con ingeniería",
    it: "Parti dall’ingegneria",
    ar: "ابدأ من الهندسة",
    ja: "エンジニアリングから始める",
  },
  ctaTitle: {
    en: "Ready to ship a connected product that actually works in the field?",
    tr: "Sahada gerçekten çalışan bir IoT ürünü çıkarmaya hazır mısınız?",
    de: "Bereit, ein IoT-Produkt auszuliefern, das im Feld wirklich funktioniert?",
    fr: "Prêt à lancer un produit IoT qui fonctionne vraiment sur le terrain ?",
    es: "¿Listo para lanzar un producto IoT que realmente funcione en campo?",
    it: "Pronto a lanciare un prodotto IoT che funziona davvero sul campo?",
    ar: "هل أنت مستعد لإطلاق منتج IoT يعمل فعلاً في الميدان؟",
    ja: "現場で本当に動く IoT 製品を出荷する準備はできていますか？",
  },
  ctaLead: {
    en: "Tell us which layer you need first — hardware, firmware, backend, mobile, web or immersive — and WillowSoft engineering will respond with a discovery plan and a realistic timeline.",
    tr: "Önceliğinizin hangi katman olduğunu anlatın: donanım, firmware, backend, mobil, web ya da VR/simülasyon. WillowSoft mühendislik ekibi size keşif planı ve gerçekçi bir zaman çizelgesiyle döner.",
    de: "Sagen Sie uns, welchen Layer Sie zuerst brauchen: Hardware, Firmware, Backend, Mobile, Web oder Immersive. WillowSoft Engineering meldet sich mit Discovery-Plan und realistischer Timeline.",
    fr: "Dites-nous quel layer est prioritaire : hardware, firmware, backend, mobile, web ou immersive. L’équipe engineering WillowSoft reviendra avec un plan de discovery et un calendrier réaliste.",
    es: "Cuéntenos qué capa necesita primero: hardware, firmware, backend, mobile, web o inmersiva. El equipo de ingeniería de WillowSoft responderá con un plan de discovery y un calendario realista.",
    it: "Dicci quale layer serve per primo: hardware, firmware, backend, mobile, web o immersive. Il team engineering WillowSoft risponderà con un piano di discovery e una timeline realistica.",
    ar: "أخبرنا أي طبقة تحتاجها أولًا: hardware أو firmware أو backend أو mobile أو web أو immersive. سيعود فريق WillowSoft الهندسي بخطة discovery وجدول زمني واقعي.",
    ja: "まず必要なレイヤーを教えてください。ハードウェア、ファームウェア、バックエンド、モバイル、Web、またはイマーシブ領域。WillowSoft のエンジニアリングチームが、ディスカバリープランと現実的なスケジュールを返します。",
  },
  faqEyebrow: {
    en: "Frequently asked",
    tr: "Sıkça Sorulan",
    de: "Häufig gestellte",
    fr: "Foire aux questions",
    es: "Preguntas frecuentes",
    it: "Domande frequenti",
    ar: "الأسئلة الشائعة",
    ja: "よくある質問",
  },
  faqTitle: {
    en: "Questions before you brief us.",
    tr: "Bize özet göndermeden önce sorular.",
    de: "Fragen vor dem Briefing.",
    fr: "Questions avant de nous envoyer le brief.",
    es: "Preguntas antes de enviarnos el brief.",
    it: "Domande prima di inviarci il brief.",
    ar: "أسئلة قبل إرسال الملخص.",
    ja: "ブリーフ前によくある質問",
  },
  faqLead: {
    en: "Engineering buyers usually arrive with the same operational questions. Here are the answers — the rest happens in the discovery call.",
    tr: "Teknik ekipler genelde benzer operasyon sorularıyla gelir. Kısa yanıtlar burada; geri kalanı keşif görüşmesinde netleşir.",
    de: "Technische Teams kommen meist mit ähnlichen operativen Fragen. Die kurzen Antworten stehen hier, der Rest klärt sich im Discovery Call.",
    fr: "Les équipes techniques arrivent souvent avec les mêmes questions opérationnelles. Les réponses courtes sont ici, le reste se précise en discovery call.",
    es: "Los equipos técnicos suelen llegar con preguntas operativas parecidas. Aquí están las respuestas cortas; el resto se aclara en la llamada de discovery.",
    it: "I team tecnici arrivano spesso con domande operative simili. Le risposte brevi sono qui; il resto si chiarisce nella discovery call.",
    ar: "تأتي الفرق التقنية غالبًا بأسئلة تشغيلية متشابهة. الإجابات المختصرة هنا، والباقي يتضح في مكالمة discovery.",
    ja: "技術チームからよく出る運用面の質問をまとめました。概要はここで確認でき、詳細はディスカバリーコールで詰めます。",
  },
};

console.log(
  JSON.stringify({
    serviceLayers: fallbackServiceLayersAsCmsItems(),
    deliverables: fallbackDeliverablesAsCmsItems(),
    processSteps: fallbackProcessStepsAsCmsItems(),
    sectionText,
  })
);
