/**
 * DANGER: Updates ALL page_content rows in Supabase. Requires --force.
 * Usage: node --env-file=.env astro-app/scripts/migrate_all.js --force
 */
import { createClient } from '@supabase/supabase-js';

if (!process.argv.includes('--force')) {
  console.error('Refusing to run: overwrites live page_content. Re-run with --force if intentional.');
  process.exit(1);
}

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

async function migrate() {
  const { data: pageContent, error } = await supabase.from('page_content').select('*');
  if (error) throw error;
  const contentMap = {};
  for (const row of pageContent) { contentMap[row.page] = row.data; }
  const addLabel = (page, key, translations) => {
    if (!contentMap[page]) contentMap[page] = {};
    contentMap[page][key] = { ...contentMap[page][key], ...translations };
  };

  const startLabels = {
    brief: { en: "Project brief", tr: "Proje Özeti", de: "Projektbriefing", fr: "Brief du projet", es: "Brief de proyecto", it: "Brief del progetto", ar: "ملخص المشروع", ja: "プロジェクト概要" },
    builderTitle: { en: "Project brief builder", tr: "Proje özeti hazırlayıcı", de: "Projektbriefing-Builder", fr: "Créateur de brief", es: "Creador de brief", it: "Generatore di brief", ar: "منشئ ملخص المشروع", ja: "要件定義ツール" },
    builderTitle2: { en: "Structured intake, faster discovery.", tr: "Yapılandırılmış alım, hızlı keşif.", de: "Strukturierte Erfassung, schnelle Erkennung.", fr: "Saisie structurée, découverte rapide.", es: "Entrada estructurada, descubrimiento más rápido.", it: "Raccolta strutturata, scoperta rapida.", ar: "استقبال منظم، استكشاف أسرع.", ja: "効率的な要件定義で開発を迅速に" },
    useStartFor: { en: "Use Start Project for", tr: "Projeye Başla formunun amacı", de: "Projekt starten für", fr: "Utiliser Démarrer un projet pour", es: "Use Iniciar proyecto para", it: "Usa Avvia progetto per", ar: "استخدم ابدأ مشروعًا لـ", ja: "「プロジェクトを開始」の対象" },
    useStartDesc: { en: "New connected products, rescue projects, backend rebuilds, mobile apps, admin panels, VR demos or website delivery.", tr: "Yeni bağlı ürünler, kurtarma projeleri, backend yeniden yapılandırması, mobil uygulamalar, yönetim panelleri, VR demoları veya web sitesi teslimatı.", de: "Neue vernetzte Produkte, Rettungsprojekte, Backend-Neubauten, mobile Apps, Admin-Panels, VR-Demos oder Website-Bereitstellung.", fr: "Nouveaux produits connectés, projets de sauvetage, reconstructions de backend, applications mobiles, panneaux d'administration, démos VR ou livraison de sites web.", es: "Nuevos productos conectados, proyectos de rescate, reconstrucciones de backend, aplicaciones móviles, paneles de administración, demostraciones de VR o entrega de sitios web.", it: "Nuovi prodotti connessi, progetti di salvataggio, ricostruzioni backend, app mobile, pannelli di amministrazione, demo VR o consegna di siti web.", ar: "المنتجات المتصلة الجديدة، مشاريع الإنقاذ، إعادة بناء الأنظمة الخلفية، تطبيقات الجوال، لوحات الإدارة، عروض الواقع الافتراضي، أو تسليم المواقع الإلكترونية.", ja: "新規の IoT 製品、既存システムの再構築、バックエンド刷新、モバイルアプリ、管理画面、VRシミュレーション、Webサイト構築。" },
    useContactFor: { en: "Use Contact for", tr: "İletişim formunun amacı", de: "Kontakt nutzen für", fr: "Utiliser Contact pour", es: "Use Contacto para", it: "Usa Contatti per", ar: "استخدم اتصل بنا لـ", ja: "「お問い合わせ」の対象" },
    useContactDesc: { en: "Office details, supplier communication, press, events or a short message without technical scope.", tr: "Ofis detayları, tedarikçi iletişimi, basın, etkinlikler veya teknik kapsam içermeyen kısa mesajlar.", de: "Bürodetails, Lieferantenkommunikation, Presse, Veranstaltungen oder eine kurze Nachricht ohne technischen Umfang.", fr: "Détails du bureau, communication avec les fournisseurs, presse, événements ou court message sans portée technique.", es: "Detalles de la oficina, comunicación con proveedores, prensa, eventos o un mensaje corto sin alcance técnico.", it: "Dettagli dell'ufficio, comunicazioni con i fornitori, stampa, eventi o un breve messaggio senza ambito tecnico.", ar: "تفاصيل المكتب، التواصل مع الموردين، الصحافة، الفعاليات، أو رسالة قصيرة دون نطاق تقني.", ja: "オフィス所在地、お取引先様からの連絡、プレス・メディア、イベント、その他開発要件のない一般的なメッセージ。" },
    afterSubmitTitle: { en: "After submit", tr: "Gönderdikten sonra", de: "Nach dem Absenden", fr: "Après l'envoi", es: "Después de enviar", it: "Dopo l'invio", ar: "بعد الإرسال", ja: "送信完了後の流れ" },
    afterSubmitDesc: { en: "We review the brief, identify missing requirements, then prepare the first technical conversation around feasibility, sequence and risk.", tr: "Özeti inceleriz, eksik gereksinimleri belirleriz ve ardından fizibilite, sıra ve risk etrafında ilk teknik görüşmeyi hazırlarız.", de: "Wir prüfen das Briefing, ermitteln fehlende Anforderungen und bereiten dann das erste technische Gespräch über Machbarkeit, Ablauf und Risiken vor.", fr: "Nous examinons le brief, identifions les exigences manquantes, puis préparons la première conversation technique sur la faisabilité, le calendrier et les risques.", es: "Revisamos el brief, identificamos requisitos faltantes y luego preparamos la primera conversación técnica sobre viabilidad, secuencia y riesgo.", it: "Esaminiamo il brief, idenfichiamo i requisiti mancanti, quindi prepariamo il primo colloquio tecnico su fattibilità, sequenza e rischi.", ar: "نراجع الملخص، ونحدد المتطلبات المفقودة، ثم نعد للمحادثة التقنية الأولى حول الجدوى والترتيب والمخاطر.", ja: "要件の確認を行い、追加情報が必要な点についてヒアリングの上、技術的な実現可能性・開発フェーズ・リスクなどを踏まえた初回面談を設定します。" },
    createProjectBrief: { en: "Create Project Brief", tr: "Proje Özeti Oluştur", de: "Projektbriefing erstellen", fr: "Créer un brief projet", es: "Crear brief de proyecto", it: "Crea brief di progetto", ar: "إنشاء ملخص المشروع", ja: "プロジェクト概要を作成" },
    generalContact: { en: "General Contact", tr: "Genel İletişim", de: "Allgemeiner Kontakt", fr: "Contact général", es: "Contacto general", it: "Contatto generale", ar: "تواصل عام", ja: "一般お問い合わせ" },
    requestFocus: { en: "Project request focus", tr: "Proje talebi odağı", de: "Fokus der Projektanfrage", fr: "Focus de la demande projet", es: "Enfoque de la solicitud", it: "Focus della richiesta", ar: "تركيز طلب المشروع", ja: "相談内容の焦点" },
    technicalScope: { en: "Technical scope", tr: "Teknik kapsam", de: "Technischer Umfang", fr: "Périmètre technique", es: "Alcance técnico", it: "Ambito tecnico", ar: "النطاق التقني", ja: "技術範囲" },
    layerPlanning: { en: "Layer planning", tr: "Katman planlama", de: "Schichtenplanung", fr: "Planification des couches", es: "Planificación por capas", it: "Pianificazione livelli", ar: "تخطيط الطبقات", ja: "レイヤー設計" },
    engineeringReview: { en: "Engineering review", tr: "Mühendislik incelemesi", de: "Engineering-Prüfung", fr: "Revue d'ingénierie", es: "Revisión de ingeniería", it: "Revisione tecnica", ar: "مراجعة هندسية", ja: "技術レビュー" },
    productsOnMarket: { en: "products on market", tr: "piyasadaki ürün", de: "Produkte am Markt", fr: "produits sur le marché", es: "productos en mercado", it: "prodotti sul mercato", ar: "منتج في السوق", ja: "市場投入済み製品" },
    happyClients: { en: "happy clients", tr: "mutlu müşteri", de: "zufriedene Kunden", fr: "clients satisfaits", es: "clientes satisfechos", it: "clienti soddisfatti", ar: "عميل سعيد", ja: "取引先企業" },
    offices: { en: "offices", tr: "ofis", de: "Büros", fr: "bureaux", es: "oficinas", it: "uffici", ar: "مكاتب", ja: "拠点" },
    trustedBy: { en: "Trusted by engineering and operations teams", tr: "Mühendislik ve operasyon ekiplerinin güvendiği yapı", de: "Vertrauen von Engineering- und Operationsteams", fr: "Approuvé par les équipes d'ingénierie et d'opérations", es: "Con la confianza de equipos de ingeniería y operaciones", it: "Scelto da team tecnici e operativi", ar: "موثوق به من فرق الهندسة والتشغيل", ja: "技術・運用チームから信頼されています" },
    customerLogos: { en: "Customer logos", tr: "Müşteri logoları", de: "Kundenlogos", fr: "Logos clients", es: "Logos de clientes", it: "Loghi clienti", ar: "شعارات العملاء", ja: "顧客ロゴ" },
    detailedFormLead: { en: "This form is intentionally more detailed than Contact. It helps WillowSoft understand whether you need one layer or an end-to-end connected product.", tr: "Bu form İletişim formundan özellikle daha detaylıdır. WillowSoft'un tek bir katmana mı yoksa uçtan uca bağlı bir ürüne mi ihtiyaç duyduğunuzu anlamasına yardımcı olur.", de: "Dieses Formular ist bewusst detaillierter als das Kontaktformular. Es hilft WillowSoft zu verstehen, ob Sie eine einzelne Schicht oder ein vollständiges vernetztes Produkt benötigen.", fr: "Ce formulaire est volontairement plus détaillé que Contact. Il aide WillowSoft à comprendre si vous avez besoin d'une couche ou d'un produit connecté complet.", es: "Este formulario es intencionalmente más detallado que Contacto. Ayuda a WillowSoft a entender si necesita una sola capa o un producto conectado de extremo a extremo.", it: "Questo modulo è volutamente più dettagliato del contatto generale. Aiuta WillowSoft a capire se serve un singolo livello o un prodotto connesso end-to-end.", ar: "هذا النموذج أكثر تفصيلاً من نموذج التواصل العام. يساعد WillowSoft على فهم ما إذا كنت تحتاج إلى طبقة واحدة أو منتج متصل متكامل.", ja: "このフォームは一般お問い合わせより詳しく設計されています。単一レイヤーの開発か、エンドツーエンドの接続製品かを把握するためのものです。" },
    scopedEngineeringRequests: { en: "Scoped engineering requests", tr: "Kapsamı belirli mühendislik talepleri", de: "Abgegrenzte Engineering-Anfragen", fr: "Demandes d'ingénierie cadrées", es: "Solicitudes de ingeniería acotadas", it: "Richieste tecniche definite", ar: "طلبات هندسية محددة النطاق", ja: "範囲が明確な技術相談" },
    generalCommunication: { en: "General communication", tr: "Genel iletişim", de: "Allgemeine Kommunikation", fr: "Communication générale", es: "Comunicación general", it: "Comunicazione generale", ar: "تواصل عام", ja: "一般連絡" },
    afterSubmitAria: { en: "What happens after you submit", tr: "Gönderdikten sonra ne olur", de: "Was nach dem Absenden passiert", fr: "Ce qui se passe après l'envoi", es: "Qué sucede después de enviar", it: "Cosa succede dopo l'invio", ar: "ماذا يحدث بعد الإرسال", ja: "送信後の流れ" },
    afterSubmission: { en: "After submission", tr: "Gönderimden sonra", de: "Nach dem Absenden", fr: "Après l'envoi", es: "Después del envío", it: "Dopo l'invio", ar: "بعد الإرسال", ja: "送信後" },
    review: { en: "Review", tr: "İnceleme", de: "Prüfung", fr: "Examen", es: "Revisión", it: "Revisione", ar: "المراجعة", ja: "確認" },
    reviewDesc: { en: "We review product layer, scope, timeline and current technical state.", tr: "Ürün katmanını, kapsamı, takvimi ve mevcut teknik durumu inceleriz.", de: "Wir prüfen Produktschicht, Umfang, Zeitplan und aktuellen technischen Stand.", fr: "Nous examinons la couche produit, le périmètre, le calendrier et l'état technique actuel.", es: "Revisamos la capa del producto, el alcance, el calendario y el estado técnico actual.", it: "Rivediamo livello di prodotto, ambito, tempistiche e stato tecnico attuale.", ar: "نراجع طبقة المنتج والنطاق والجدول الزمني والحالة التقنية الحالية.", ja: "製品レイヤー、範囲、スケジュール、現在の技術状態を確認します。" },
    clarify: { en: "Clarify", tr: "Netleştirme", de: "Klären", fr: "Clarifier", es: "Aclarar", it: "Chiarire", ar: "التوضيح", ja: "明確化" },
    clarifyDesc: { en: "We ask for missing requirements, constraints, drawings, APIs or deployment goals.", tr: "Eksik gereksinimleri, kısıtları, çizimleri, API'leri veya kurulum hedeflerini sorarız.", de: "Wir fragen fehlende Anforderungen, Einschränkungen, Zeichnungen, APIs oder Deployment-Ziele ab.", fr: "Nous demandons les exigences manquantes, contraintes, schémas, APIs ou objectifs de déploiement.", es: "Pedimos requisitos faltantes, restricciones, planos, APIs u objetivos de despliegue.", it: "Chiediamo requisiti mancanti, vincoli, disegni, API o obiettivi di installazione.", ar: "نطلب المتطلبات الناقصة والقيود والرسومات وواجهات API أو أهداف النشر.", ja: "不足要件、制約、図面、API、導入目標を確認します。" },
    call: { en: "Call", tr: "Görüşme", de: "Gespräch", fr: "Appel", es: "Llamada", it: "Call", ar: "مكالمة", ja: "面談" },
    callDesc: { en: "Engineering aligns on feasibility, risks, rough sequence and next deliverables.", tr: "Mühendislik ekibi fizibilite, riskler, genel sıra ve sonraki teslimatlar üzerinde hizalanır.", de: "Engineering stimmt Machbarkeit, Risiken, grobe Abfolge und nächste Lieferobjekte ab.", fr: "L'ingénierie aligne faisabilité, risques, séquence et prochains livrables.", es: "Ingeniería alinea viabilidad, riesgos, secuencia general y próximos entregables.", it: "Il team tecnico allinea fattibilità, rischi, sequenza e prossimi deliverable.", ar: "يوائم الفريق الهندسي الجدوى والمخاطر والتسلسل العام والتسليمات التالية.", ja: "実現性、リスク、進行順序、次の成果物を技術チームで整理します。" },
    plan: { en: "Plan", tr: "Plan", de: "Plan", fr: "Plan", es: "Plan", it: "Piano", ar: "الخطة", ja: "計画" },
    planDesc: { en: "You receive a practical direction for prototype, platform rebuild or full delivery.", tr: "Prototip, platform yeniden yapılandırması veya tam teslimat için uygulanabilir bir yön alırsınız.", de: "Sie erhalten eine praktische Richtung für Prototyp, Plattform-Rebuild oder vollständige Lieferung.", fr: "Vous recevez une direction concrète pour prototype, refonte plateforme ou livraison complète.", es: "Recibe una dirección práctica para prototipo, reconstrucción de plataforma o entrega completa.", it: "Ricevi una direzione pratica per prototipo, rebuild piattaforma o consegna completa.", ar: "تحصل على اتجاه عملي للنموذج الأولي أو إعادة بناء المنصة أو التسليم الكامل.", ja: "プロトタイプ、基盤再構築、フル開発に向けた現実的な方針を提示します。" },
    faqEyebrow: { en: "Frequently asked", tr: "Sıkça sorulanlar", de: "Häufig gestellte Fragen", fr: "Questions fréquentes", es: "Preguntas frecuentes", it: "Domande frequenti", ar: "أسئلة مكررة", ja: "よくある質問" },
    faqTitle: { en: "Questions about starting a project.", tr: "Projeye başlama ile ilgili sorular.", de: "Fragen zum Projektstart.", fr: "Questions sur le démarrage d'un projet.", es: "Preguntas sobre cómo iniciar un proyecto.", it: "Domande sull'avvio di un progetto.", ar: "أسئلة حول بدء مشروع.", ja: "プロジェクト開始に関するご質問" },
    faqLead: { en: "Here are answers to common questions about our client onboarding, timelines, and technical project delivery.", tr: "Müşteri onboarding sürecimiz, zaman planlarımız ve teknik proje teslimatımız hakkında sıkça sorulan soruların yanıtları.", de: "Hier finden Sie Antworten auf häufige Fragen zu Onboarding, Zeitplänen und technischer Projektabwicklung.", fr: "Voici les réponses aux questions courantes sur l'intégration des clients, les délais et la livraison technique du projet.", es: "Aquí encontrará respuestas a preguntas comunes sobre nuestra incorporación de clientes, plazos y entrega técnica de proyectos.", it: "Ecco le risposte alle domande comuni sull'onboarding dei clienti, sulle tempistiche e sulla consegna tecnica del progetto.", ar: "إليك إجابات الأسئلة الشائعة حول إعداد العملاء والجدول الزمني وتسليم المشاريع التقنية.", ja: "クライアント登録、納期、開発プロジェクトの納品に関する一般的な質問への回答です。" }
  };
  Object.entries(startLabels).forEach(([k, v]) => addLabel('startProject', k, v));

  const steps = {
    en: ["Product idea", "Required layers", "Timeline and budget", "Contact details"],
    tr: ["Ürün fikri", "Gerekli katmanlar", "Süreç ve bütçe", "İletişim bilgileri"],
    de: ["Produktidee", "Benötigte Ebenen", "Zeitplan und Budget", "Kontaktdaten"],
    fr: ["Idée de produit", "Couches requises", "Calendrier et budget", "Coordonnées"],
    es: ["Idea de producto", "Capas requeridas", "Cronograma y presupuesto", "Datos de contacto"],
    it: ["Idea del prodotto", "Livelli richiesti", "Tempistiche e budget", "Dettagli di contatto"],
    ar: ["فكرة المنتج", "الطبقات المطلوبة", "الجدول الزمني والميزانية", "تفاصيل الاتصال"],
    ja: ["プロダクトアイデア", "必要なレイヤー", "納期・ご予算", "ご連絡先情報"]
  };
  const stepsTransformed = {};
  for(let l of Object.keys(steps)) { stepsTransformed[l] = JSON.stringify(steps[l]); }
  addLabel('startProject', 'steps', stepsTransformed);

  const servicesLabels = {
    exploreOther: { en: "Explore other services", tr: "Diğer hizmetleri keşfedin", de: "Weitere Dienste erkunden", fr: "Explorer d'autres services", es: "Explorar otros servicios", it: "Esplora altri servizi", ar: "استكشف خدمات أخرى", ja: "その他のサービスを見る" },
    talkToEngineering: { en: "Talk to Engineering", tr: "Mühendislerimizle Görüşün", de: "Mit Engineering sprechen", fr: "Parler à l'ingénierie", es: "Hablar con ingeniería", it: "Parla con il team", ar: "تحدث إلى الهندسة", ja: "技術チームへ相談" },
    faqTitle: { en: "Questions about WillowSoft services.", tr: "WillowSoft hizmetleri hakkında sorular.", de: "Fragen zu WillowSoft-Diensten.", fr: "Questions sur les services WillowSoft.", es: "Preguntas sobre los servicios de WillowSoft.", it: "Domande sui servizi WillowSoft.", ar: "أسئلة حول خدمات WillowSoft.", ja: "WillowSoftのサービスに関するご質問" },
    faqLead: { en: "Find answers to common questions about how we approach embedded hardware, cloud architecture, and industrial design.", tr: "Gömülü donanım, bulut mimarisi ve endüstriyel tasarıma yaklaşımımız hakkındaki sık sorulan soruların yanıtlarını bulun.", de: "Antworten auf häufige Fragen zu Embedded-Hardware, Cloud-Architektur und Industriedesign.", fr: "Trouvez des réponses aux questions courantes sur notre approche du matériel embarqué, de l'architecture cloud et du design industriel.", es: "Encuentre respuestas a preguntas comunes sobre nuestro enfoque de hardware integrado, arquitectura en la nube y diseño industrial.", it: "Trova le risposte alle domande comuni sul nostro approccio all'hardware integrato, all'architettura cloud e al design industriale.", ar: "اعثر على إجابات للأسئلة الشائعة حول نهجنا تجاه الأجهزة المدمجة والبنية السحابية والتصميم الصناعي.", ja: "組み込みハードウェア、クラウドアーキテクチャ、工業デザインへのアプローチに関するよくある質問にお答えします。" }
  };
  Object.entries(servicesLabels).forEach(([k, v]) => addLabel('services', k, v));

  const companyLabels = {
    teamEyebrow: { en: "The Team", tr: "Ekip", de: "Das Team", fr: "L'équipe", es: "El equipo", it: "Il team", ar: "الفريق", ja: "チーム" },
    teamTitle: { en: "Core Engineering", tr: "Çekirdek Mühendislik", de: "Kern-Engineering", fr: "Ingénierie principale", es: "Ingeniería principal", it: "Ingegneria di base", ar: "الهندسة الأساسية", ja: "コアエンジニアリング" },
    teamLead: { en: "A small, highly specialized team of embedded and backend engineers.", tr: "Gömülü sistemler ve arka uç mühendislerinden oluşan küçük, yüksek düzeyde uzmanlaşmış bir ekip.", de: "Ein kleines, hochspezialisiertes Team aus Embedded- und Backend-Ingenieuren.", fr: "Une petite équipe hautement spécialisée d'ingénieurs embarqués et backend.", es: "Un equipo pequeño y altamente especializado de ingenieros de sistemas integrados y backend.", it: "Un piccolo team altamente specializzato di ingegneri embedded e backend.", ar: "فريق صغير ومتخصص للغاية من مهندسي الأنظمة المدمجة والواجهات الخلفية.", ja: "組み込みエンジニアとバックエンドエンジニアからなる、小規模で高度に専門化されたチーム。" },
    principlesEyebrow: { en: "Principles", tr: "İlkeler", de: "Prinzipien", fr: "Principes", es: "Principios", it: "Principi", ar: "المبادئ", ja: "原則" },
    principlesTitle: { en: "Engineering philosophy", tr: "Mühendislik felsefesi", de: "Engineering-Philosophie", fr: "Philosophie d'ingénierie", es: "Filosofía de ingeniería", it: "Filosofia ingegneristica", ar: "الفلسفة الهندسية", ja: "エンジニアリング哲学" },
    principlesLead: { en: "How we approach complex hardware and software challenges.", tr: "Karmaşık donanım ve yazılım zorluklarına nasıl yaklaşıyoruz.", de: "Wie wir komplexe Hardware- und Softwareherausforderungen angehen.", fr: "Comment nous abordons les défis matériels et logiciels complexes.", es: "Cómo abordamos los complejos desafíos de hardware y software.", it: "Come affrontiamo le complesse sfide hardware e software.", ar: "كيف نتعامل مع التحديات المعقدة للأجهزة والبرامج.", ja: "複雑なハードウェアとソフトウェアの課題に対する私たちのアプローチ。" },
    faqTitle: { en: "Questions about WillowSoft.", tr: "WillowSoft hakkında sorular.", de: "Fragen zu WillowSoft.", fr: "Questions sur WillowSoft.", es: "Preguntas sobre WillowSoft.", it: "Domande su WillowSoft.", ar: "أسئلة حول WillowSoft.", ja: "WillowSoftについてのご質問" },
    faqLead: { en: "Find answers to common questions about our history, team structure, and partnerships.", tr: "Tarihçemiz, ekip yapımız ve ortaklıklarımız hakkındaki sık sorulan soruların yanıtlarını bulun.", de: "Finden Sie Antworten auf häufige Fragen zu unserer Geschichte, Teamstruktur und Partnerschaften.", fr: "Trouvez des réponses aux questions courantes sur notre histoire, la structure de notre équipe et nos partenariats.", es: "Encuentre respuestas a preguntas comunes sobre nuestra historia, estructura del equipo y asociaciones.", it: "Trova le risposte alle domande comuni sulla nostra storia, sulla struttura del team e sulle partnership.", ar: "اعثر على إجابات للأسئلة الشائعة حول تاريخنا وهيكل فريقنا وشراكاتنا.", ja: "当社の沿革、チーム構成、パートナーシップに関するよくある質問にお答えします。" },
    openAdmin: { en: "Open Admin Panel", tr: "Yönetici Panelini Aç", de: "Admin-Panel öffnen", fr: "Ouvrir le panneau d'administration", es: "Abrir panel de administración", it: "Apri pannello di amministrazione", ar: "افتح لوحة الإدارة", ja: "管理画面を開く" },
    heroAlt: { en: "WillowSoft engineering updates", tr: "WillowSoft mühendislik haberleri", de: "WillowSoft Engineering-Neuigkeiten", fr: "Actualités d'ingénierie WillowSoft", es: "Actualizaciones de ingeniería de WillowSoft", it: "Aggiornamenti tecnici WillowSoft", ar: "تحديثات WillowSoft الهندسية", ja: "WillowSoft エンジニアリングニュース" },
    latestUpdates: { en: "Latest Updates", tr: "Son Güncellemeler", de: "Aktuelle Meldungen", fr: "Dernières actualités", es: "Últimas novedades", it: "Ultimi aggiornamenti", ar: "آخر التحديثات", ja: "最新情報" },
    proofTitle: { en: "Proof that WillowSoft is active in the field.", tr: "WillowSoft'un sahada aktif olduğunu gösteren kanıtlar.", de: "Nachweise, dass WillowSoft im Feld aktiv ist.", fr: "La preuve que WillowSoft est actif sur le terrain.", es: "Pruebas de que WillowSoft está activo sobre el terreno.", it: "Prove concrete dell'attività di WillowSoft sul campo.", ar: "دليل على أن WillowSoft نشطة في الميدان.", ja: "WillowSoft が現場で活動していることを示す実績。" },
    ctaEyebrow: { en: "Turn proof into pipeline", tr: "Kanıtı fırsat akışına dönüştür", de: "Nachweise in Anfragen verwandeln", fr: "Transformer la preuve en opportunités", es: "Convertir pruebas en oportunidades", it: "Trasforma le prove in opportunità", ar: "حوّل الدليل إلى فرص", ja: "実績を商談につなげる" },
    ctaTitle: { en: "Use news, events and product launches to drive qualified leads.", tr: "Haberleri, etkinlikleri ve ürün lansmanlarını nitelikli taleplere dönüştürün.", de: "Nutzen Sie News, Events und Produktstarts für qualifizierte Anfragen.", fr: "Utilisez les actualités, événements et lancements produits pour générer des prospects qualifiés.", es: "Use noticias, eventos y lanzamientos de producto para generar clientes potenciales cualificados.", it: "Usa notizie, eventi e lanci di prodotto per generare lead qualificati.", ar: "استخدم الأخبار والفعاليات وإطلاق المنتجات لجذب عملاء محتملين مؤهلين.", ja: "ニュース、イベント、製品発表を有望な問い合わせにつなげます。" },
    ctaLead: { en: "The admin panel can add new news items without touching code. Featured updates can later be surfaced on Home and Company pages.", tr: "Yönetici paneli kod yazmadan yeni haber ekleyebilir. Öne çıkan güncellemeler daha sonra Ana Sayfa ve Şirket sayfalarında gösterilebilir.", de: "Über das Admin-Panel lassen sich neue Meldungen ohne Codeänderung hinzufügen. Ausgewählte Updates können später auf Startseite und Unternehmensseite erscheinen.", fr: "Le panneau d'administration permet d'ajouter des actualités sans modifier le code. Les mises à jour importantes peuvent ensuite apparaître sur les pages Accueil et Entreprise.", es: "El panel de administración permite añadir noticias sin tocar código. Las novedades destacadas pueden mostrarse después en Inicio y Empresa.", it: "Il pannello admin permette di aggiungere news senza modificare il codice. Gli aggiornamenti in evidenza possono poi comparire in Home e nella pagina Azienda.", ar: "يمكن للوحة الإدارة إضافة أخبار جديدة دون تعديل الكود. ويمكن لاحقاً عرض التحديثات المميزة في الصفحة الرئيسية وصفحة الشركة.", ja: "管理画面からコードを触らずにニュースを追加できます。重要な更新は後でホームや会社情報ページにも表示できます。" }
  };
  Object.entries(companyLabels).forEach(([k, v]) => addLabel('company', k, v));

  const solutionsLabels = {
    faqTitle: { en: "Questions about WillowSoft solutions.", tr: "WillowSoft çözümleri hakkında sorular.", de: "Fragen zu WillowSoft-Lösungen.", fr: "Questions sur les solutions WillowSoft.", es: "Preguntas sobre las soluciones de WillowSoft.", it: "Domande sulle soluzioni WillowSoft.", ar: "أسئلة حول حلول WillowSoft.", ja: "WillowSoftのソリューションについてのご質問" },
    faqLead: { en: "Answers to the most common questions about our IoT capabilities and deployments.", tr: "IoT yeteneklerimiz ve kurulumlarımız hakkındaki en yaygın soruların yanıtları.", de: "Antworten auf die häufigsten Fragen zu unseren IoT-Fähigkeiten und -Bereitstellungen.", fr: "Réponses aux questions les plus courantes sur nos capacités IoT et nos déploiements.", es: "Respuestas a las preguntas más comunes sobre nuestras capacidades y despliegues de IoT.", it: "Risposte alle domande più comuni sulle nostre capacità e implementazioni IoT.", ar: "إجابات على الأسئلة الأكثر شيوعًا حول قدرات إنترنت الأشياء وعمليات النشر لدينا.", ja: "IoT機能と導入実績に関する最も一般的な質問への回答です。" }
  };
  Object.entries(solutionsLabels).forEach(([k, v]) => addLabel('solutions', k, v));

  const productsLabels = {
    productFeatures: { en: "Product features", tr: "Ürün özellikleri", de: "Produktmerkmale", fr: "Caractéristiques du produit", es: "Características del producto", it: "Caratteristiche del prodotto", ar: "ميزات المنتج", ja: "製品の特長" },
    technicalSpecs: { en: "Technical specifications", tr: "Teknik özellikler", de: "Technische Spezifikationen", fr: "Spécifications techniques", es: "Especificaciones técnicas", it: "Specifiche tecniche", ar: "المواصفات الفنية", ja: "技術仕様" },
    relatedProducts: { en: "Related products", tr: "İlgili ürünler", de: "Verwandte Produkte", fr: "Produits connexes", es: "Productos relacionados", it: "Prodotti correlati", ar: "منتجات ذات صلة", ja: "関連製品" },
    faqTitle: { en: "Questions about WillowSoft products.", tr: "WillowSoft ürünleri hakkında sorular.", de: "Fragen zu WillowSoft-Produkten.", fr: "Questions sur les produits WillowSoft.", es: "Preguntas sobre los productos de WillowSoft.", it: "Domande sui prodotti WillowSoft.", ar: "أسئلة حول منتجات WillowSoft.", ja: "WillowSoftの製品についてのご質問" },
    faqLead: { en: "Find answers to common questions about compatibility, warranties, and bulk ordering.", tr: "Uyumluluk, garantiler ve toplu siparişler hakkındaki sık sorulan soruların yanıtlarını bulun.", de: "Finden Sie Antworten auf häufige Fragen zu Kompatibilität, Garantien und Großbestellungen.", fr: "Trouvez des réponses aux questions courantes sur la compatibilité, les garanties et les commandes groupées.", es: "Encuentre respuestas a preguntas comunes sobre compatibilidad, garantías y pedidos al por mayor.", it: "Trova le risposte alle domande comuni su compatibilità, garanzie e ordini all'ingrosso.", ar: "اعثر على إجابات للأسئلة الشائعة حول التوافق والضمانات والطلبات بالجملة.", ja: "互換性、保証、大量注文に関するよくある質問への回答をご覧ください。" }
  };
  Object.entries(productsLabels).forEach(([k, v]) => addLabel('products', k, v));

  for (const page of Object.keys(contentMap)) {
    await supabase.from('page_content').update({ data: contentMap[page] }).eq('page', page);
  }
  
  console.log("Migration complete!");
}

migrate().catch(console.error);
