-- WillowSoft unified publishing center
-- Server-side publishing only: every table below is private and accessed with
-- the service-role client after the existing admin session/permission checks.

create table if not exists public.social_accounts (
  id                    uuid primary key default gen_random_uuid(),
  platform              text not null check (platform in ('linkedin', 'instagram', 'x')),
  external_account_id   text not null,
  display_name          text not null,
  username              text,
  status                text not null default 'connected'
                        check (status in ('connected', 'expired', 'attention', 'disconnected')),
  scopes                text[] not null default '{}',
  token_ciphertext      text,
  refresh_ciphertext    text,
  token_expires_at      timestamptz,
  metadata              jsonb not null default '{}'::jsonb,
  connected_by          uuid references public.admin_users(id) on delete set null,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  unique (platform, external_account_id)
);

create table if not exists public.publication_campaigns (
  id                    uuid primary key default gen_random_uuid(),
  news_id               text references public.news(id) on delete set null,
  title                 text not null default '',
  canonical_content     jsonb not null default '{}'::jsonb,
  status                text not null default 'draft'
                        check (status in (
                          'draft', 'ready', 'scheduled', 'queued', 'publishing',
                          'partially_published', 'published', 'failed', 'cancelled'
                        )),
  scheduled_at          timestamptz,
  timezone              text not null default 'Europe/Istanbul',
  idempotency_key       text unique,
  created_by            uuid references public.admin_users(id) on delete set null,
  updated_by            uuid references public.admin_users(id) on delete set null,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create table if not exists public.publication_targets (
  id                    uuid primary key default gen_random_uuid(),
  campaign_id           uuid not null references public.publication_campaigns(id) on delete cascade,
  platform              text not null check (platform in ('website', 'linkedin', 'instagram', 'x')),
  account_id            uuid references public.social_accounts(id) on delete set null,
  enabled               boolean not null default true,
  overrides             jsonb not null default '{}'::jsonb,
  status                text not null default 'pending'
                        check (status in (
                          'pending', 'validating', 'uploading_media', 'queued',
                          'publishing', 'published', 'failed', 'retrying', 'cancelled'
                        )),
  attempts              integer not null default 0,
  external_post_id      text,
  external_url          text,
  error_code            text,
  error_message         text,
  retryable             boolean not null default false,
  published_at          timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  unique (campaign_id, platform)
);

create table if not exists public.publication_events (
  id                    bigint generated by default as identity primary key,
  campaign_id           uuid not null references public.publication_campaigns(id) on delete cascade,
  target_id             uuid references public.publication_targets(id) on delete cascade,
  event_type            text not null,
  message               text,
  metadata              jsonb not null default '{}'::jsonb,
  actor_id              uuid references public.admin_users(id) on delete set null,
  created_at            timestamptz not null default now()
);

create index if not exists publication_campaigns_status_schedule_idx
  on public.publication_campaigns (status, scheduled_at);
create index if not exists publication_campaigns_updated_idx
  on public.publication_campaigns (updated_at desc);
create index if not exists publication_targets_campaign_idx
  on public.publication_targets (campaign_id, platform);
create index if not exists publication_targets_status_idx
  on public.publication_targets (status, updated_at);
create index if not exists publication_events_campaign_idx
  on public.publication_events (campaign_id, created_at desc);

alter table public.social_accounts enable row level security;
alter table public.publication_campaigns enable row level security;
alter table public.publication_targets enable row level security;
alter table public.publication_events enable row level security;

drop policy if exists "deny_all" on public.social_accounts;
create policy "deny_all" on public.social_accounts using (false) with check (false);
drop policy if exists "deny_all" on public.publication_campaigns;
create policy "deny_all" on public.publication_campaigns using (false) with check (false);
drop policy if exists "deny_all" on public.publication_targets;
create policy "deny_all" on public.publication_targets using (false) with check (false);
drop policy if exists "deny_all" on public.publication_events;
create policy "deny_all" on public.publication_events using (false) with check (false);

comment on table public.publication_campaigns is
  'Canonical content and orchestration state for Website, LinkedIn, Instagram and X publishing.';
comment on column public.publication_campaigns.idempotency_key is
  'Prevents accidental duplicate publication when a client retries the same command.';
comment on column public.social_accounts.token_ciphertext is
  'Optional AES-GCM encrypted OAuth token; never return this field to the browser.';
